//! Phase 3 — write the bootstrap into the store: config, architecture overview, module docs, index.
//! Generated facts live between markers and are refreshed on every run; text written by people or
//! agents (Purpose, Overview, summaries once deepened) is preserved.
use super::history::History;
use super::scan::{Inventory, Module};
use crate::app::App;
use crate::config::Style;
use crate::repo::Repo;
use crate::store::{Entry, FmValue, Store};
use crate::util;
use anyhow::Result;
use std::fmt::Write as _;

pub const FACTS_START: &str = "<!-- kontext:facts:start — generated by `kontext init`, refreshed on every run -->";
pub const FACTS_END: &str = "<!-- kontext:facts:end -->";

pub fn store_dir(app: &App) -> String {
    app.cfg().store.dir.trim_end_matches('/').to_string()
}

/// Write `<store>/kontext.toml` when no shared config exists yet. Returns the path written.
pub fn write_config_if_missing(repo: &Repo, store_dir: &str, project: &str, inv: &Inventory) -> Result<Option<String>> {
    if crate::config::shared_config_candidates(repo).iter().any(|p| p.exists()) {
        return Ok(None);
    }
    let rel = format!("{store_dir}/kontext.toml");
    let mut s = String::new();
    let _ = writeln!(s, "# kontext — shared configuration for this repository (committed, reviewed like code).");
    let _ = writeln!(s, "# Personal adapters (OpenViking, codegraph, Serena, …) belong in ~/.config/kontext/config.toml;");
    let _ = writeln!(s, "# adapters declared here only run after each teammate reviews them with `kontext trust`.\n");
    let _ = writeln!(s, "[project]\nname = \"{}\"\n", project.replace('"', ""));
    let _ = writeln!(s, "[store]\ndir = \"{store_dir}\"\n");
    if let Some(adr) = inv.adr_dirs.first() {
        let _ = writeln!(s, "# Existing ADRs were detected — kontext reads and writes decisions there, in the same style.");
        let _ = writeln!(
            s,
            "[store.kinds.decision]\npath = \"{}\"\nstyle = \"{}\"\nnumbering = \"{}\"\ntrailer = \"Decision\"\n",
            adr.path, adr.style, adr.numbering
        );
    }
    let _ = writeln!(
        s,
        "[hooks]\n# prepare-commit-msg adds trailers such as `Decision: <id>` for knowledge committed with code\ntrailers = true\n"
    );
    let _ =
        writeln!(s, "[secrets]\n# \"store\": scan knowledge files only · \"staged\": every staged text file · \"off\"\nscan = \"store\"");
    util::write_atomic(&repo.abs(&rel), &s)?;
    Ok(Some(rel))
}

fn facts_block(facts: &str) -> String {
    format!("{FACTS_START}\n{}\n{FACTS_END}\n", facts.trim_end())
}

fn replace_facts(body: &str, facts: &str) -> Option<String> {
    let s = body.find(FACTS_START.split(" —").next().unwrap_or(FACTS_START))?;
    let e = body.find(FACTS_END)?;
    if e < s {
        return None;
    }
    Some(format!("{}{}{}", &body[..s], facts_block(facts), body[e + FACTS_END.len()..].trim_start_matches('\n')))
}

fn pct(part: usize, total: usize) -> String {
    format!("{}%", (part * 100 + total / 2).checked_div(total).unwrap_or(0))
}

pub fn stack_line(inv: &Inventory) -> String {
    let mut parts: Vec<String> =
        inv.languages.iter().filter(|l| crate::init::scan::is_code(&l.lang)).take(3).map(|l| l.lang.clone()).collect();
    parts.extend(inv.workspace.iter().filter(|w| !matches!(w.as_str(), "uv")).cloned());
    parts.extend(inv.stack.iter().take(9).cloned());
    let mut seen = Vec::new();
    parts.retain(|p| {
        if seen.contains(p) {
            false
        } else {
            seen.push(p.clone());
            true
        }
    });
    parts.join(" · ")
}

fn overview_facts(inv: &Inventory, hist: &History, modules: &[&Module], summaries: &std::collections::HashMap<String, String>) -> String {
    let mut f = String::new();
    let code_total: usize = inv.languages.iter().filter(|l| crate::init::scan::is_code(&l.lang)).map(|l| l.lines).sum();
    let _ = writeln!(f, "## Stack\n");
    let langs: Vec<String> = inv
        .languages
        .iter()
        .filter(|l| crate::init::scan::is_code(&l.lang))
        .take(6)
        .map(|l| format!("{} {} ({} files)", l.lang, pct(l.lines, code_total), l.files))
        .collect();
    let _ = writeln!(f, "- Languages: {}", if langs.is_empty() { "—".into() } else { langs.join(", ") });
    if !inv.workspace.is_empty() {
        let _ = writeln!(f, "- Workspace: {}", inv.workspace.join(", "));
    }
    if !inv.stack.is_empty() {
        let _ = writeln!(f, "- Frameworks & platforms: {}", inv.stack.join(", "));
    }
    if !inv.tooling.is_empty() {
        let _ = writeln!(f, "- Tooling: {}", inv.tooling.join(", "));
    }
    if !inv.ci.is_empty() {
        let _ = writeln!(f, "- CI: {}", inv.ci.iter().take(8).cloned().collect::<Vec<_>>().join(", "));
    }
    let _ = writeln!(f, "- Size: {} tracked files, {} source files, {} lines of code", inv.files, inv.source_files, inv.lines);
    if !modules.is_empty() {
        let _ = writeln!(f, "\n## Layout\n\n| Module | Kind | Language | Files | What it is |\n|---|---|---|---|---|");
        for m in modules {
            // an agent-written summary beats the README description
            let what = summaries
                .get(&m.id)
                .map(String::as_str)
                .or(m.description.as_deref())
                .map(|d| util::truncate_chars(&util::one_line(d), 90))
                .unwrap_or_default()
                .replace('|', "/");
            let _ = writeln!(f, "| `{}` | {} | {} | {} | {} |", m.path, m.kind, m.language, m.files, what);
        }
        let rest: Vec<&str> = inv.modules.iter().filter(|m| !modules.iter().any(|d| d.path == m.path)).map(|m| m.path.as_str()).collect();
        if !rest.is_empty() {
            let more = if rest.len() > 40 { format!(" (+{} more)", rest.len() - 40) } else { String::new() };
            let _ = writeln!(
                f,
                "\nAlso ({} without a module doc; raise `init.max_module_docs` to document them): {}{more}",
                rest.len(),
                rest.iter().take(40).map(|p| format!("`{p}`")).collect::<Vec<_>>().join(", ")
            );
        }
    }
    let mut work = Vec::new();
    if !inv.scripts.is_empty() {
        let s: Vec<String> = inv.scripts.iter().take(8).map(|(k, _)| format!("`npm run {k}`")).collect();
        work.push(format!("- Scripts (root package.json): {}", s.join(", ")));
    }
    if !inv.agent_files.is_empty() {
        let more =
            if inv.agent_files.len() > 8 { format!(" (+{} more in module directories)", inv.agent_files.len() - 8) } else { String::new() };
        work.push(format!("- Agent rules: {}{more}", inv.agent_files.iter().take(8).cloned().collect::<Vec<_>>().join(", ")));
    }
    if !inv.doc_dirs.is_empty() {
        work.push(format!("- Docs: {}", inv.doc_dirs.iter().take(14).cloned().collect::<Vec<_>>().join(", ")));
    }
    if let Some(adr) = inv.adr_dirs.first() {
        work.push(format!("- Decision records: `{}` ({} ADRs, {} style)", adr.path, adr.count, adr.style));
    }
    if !inv.env_names.is_empty() {
        work.push(format!(
            "- Environment variables (names from .env examples): {}",
            inv.env_names.iter().take(20).cloned().collect::<Vec<_>>().join(", ")
        ));
    }
    if !inv.submodules.is_empty() {
        work.push(format!("- Git submodules: {}", inv.submodules.join(", ")));
    }
    if !work.is_empty() {
        let _ = writeln!(f, "\n## Working here\n\n{}", work.join("\n"));
    }
    if hist.commits > 0 {
        let mut line = format!(
            "- {} commits{} by {} contributor(s)",
            hist.commits,
            hist.first_date.as_deref().map(|d| format!(" since {d}")).unwrap_or_default(),
            hist.contributors
        );
        if hist.conventional_ratio >= 0.5 {
            let _ = write!(line, "; Conventional Commits ({})", pct((hist.conventional_ratio * 100.0) as usize, 100));
        }
        if hist.ticket_ratio >= 0.2
            && let Some(t) = &hist.ticket_example
        {
            let _ = write!(line, "; subjects reference tickets like `{t}`");
        }
        let _ = writeln!(f, "\n## History\n\n{line}");
        if !hist.clusters.is_empty() {
            let areas: Vec<String> =
                hist.clusters.iter().take(6).map(|c| c.module.clone().unwrap_or_else(|| "repository".into())).collect();
            let _ = writeln!(f, "- Decision-shaped commits cluster in: {}", areas.join(", "));
        }
    }
    f
}

fn module_facts(m: &Module, inv: &Inventory) -> String {
    let mut f = String::from("## Facts\n\n");
    let tests = if m.tests > 0 { format!(" ({} tests)", m.tests) } else { String::new() };
    let _ = writeln!(f, "- **Kind:** {} · {} · {} files{tests} · {} lines", m.kind, m.language, m.files, m.lines);
    if m.name != m.path {
        let _ = writeln!(f, "- **Package:** `{}`", m.name);
    }
    if !m.manifests.is_empty() {
        let _ = writeln!(f, "- **Manifest:** {}", m.manifests.join(", "));
    }
    if !m.deps.is_empty() {
        let _ = writeln!(f, "- **Depends on:** {}", m.deps.iter().map(|d| format!("`{d}`")).collect::<Vec<_>>().join(", "));
    }
    if !m.dependents.is_empty() {
        let _ = writeln!(f, "- **Used by:** {}", m.dependents.iter().take(12).map(|d| format!("`{d}`")).collect::<Vec<_>>().join(", "));
    }
    if !m.key_files.is_empty() {
        let files: Vec<String> =
            m.key_files.iter().take(8).map(|(p, l)| format!("`{}` ({l})", p.strip_prefix(&format!("{}/", m.path)).unwrap_or(p))).collect();
        let _ = writeln!(f, "- **Key files:** {}", files.join(", "));
    }
    if !m.symbols.is_empty() {
        let names: Vec<String> =
            m.symbols.iter().take(16).map(|s| s.split_once(' ').map(|(_, n)| n.to_string()).unwrap_or_else(|| s.clone())).collect();
        let _ = writeln!(f, "- **Exports:** {}", names.join(", "));
    }
    if !m.ext_deps.is_empty() {
        let _ = writeln!(f, "- **Packages:** {}", m.ext_deps.iter().take(12).cloned().collect::<Vec<_>>().join(", "));
    }
    if !m.docs.is_empty() {
        let _ = writeln!(f, "- **Docs:** {}", m.docs.join(", "));
    }
    let nested_agents: Vec<&String> =
        inv.agent_files.iter().filter(|a| a.starts_with(&format!("{}/", m.path)) && !m.docs.contains(a)).collect();
    if !nested_agents.is_empty() {
        let _ = writeln!(f, "- **Agent rules:** {}", nested_agents.iter().map(|s| s.as_str()).collect::<Vec<_>>().join(", "));
    }
    if m.churn > 0 {
        let _ = writeln!(
            f,
            "- **Activity:** {} file changes in history{}",
            m.churn,
            m.last_change.as_deref().map(|d| format!(", last {d}")).unwrap_or_default()
        );
    }
    f
}

pub fn documented_modules(inv: &Inventory, max: usize) -> Vec<&Module> {
    let mut mods: Vec<&Module> = inv.modules.iter().collect();
    mods.sort_by_key(|m| m.rank);
    let substantial: Vec<&Module> = mods.iter().copied().filter(|m| !matches!(m.kind.as_str(), "tests" | "example" | "docs")).collect();
    let mut chosen = if substantial.len() >= 3 { substantial } else { mods };
    chosen.truncate(max);
    chosen
}

pub fn module_rel(store_dir: &str, m: &Module) -> String {
    format!("{store_dir}/architecture/modules/{}.md", util::slugify(&m.path, 70))
}

#[derive(Debug, Default)]
pub struct RenderReport {
    pub overview_written: bool,
    pub modules_new: usize,
    pub modules_updated: usize,
    pub index_changed: bool,
}

pub fn render_all(app: &App, inv: &Inventory, hist: &History) -> Result<RenderReport> {
    let mut rep = RenderReport::default();
    let dir = store_dir(app);
    let store = Store::new(&app.repo, app.cfg());
    let mods = documented_modules(inv, app.cfg().init.max_module_docs);

    // overview
    let ov_rel = format!("{dir}/architecture/overview.md");
    let (existing_entries, _) = store.load_all();
    let summaries: std::collections::HashMap<String, String> = existing_entries
        .iter()
        .filter(|e| e.id.starts_with("mod-") && e.get_extra("deepened").is_some())
        .filter_map(|e| e.summary.clone().filter(|s| !s.trim().is_empty()).map(|s| (e.id.clone(), s)))
        .collect();
    let facts = overview_facts(inv, hist, &mods, &summaries);
    let existing = std::fs::read_to_string(app.repo.abs(&ov_rel)).ok().map(|t| Entry::parse(&ov_rel, &t, "architecture"));
    let mut ov = existing.clone().unwrap_or_else(|| {
        let purpose = match (&inv.readme_summary, &inv.root_description) {
            (Some(r), _) => {
                format!("From the README: {r}\n\n_Pending: an agent confirms and sharpens this during `kontext init` (task `purpose`)._")
            }
            (None, Some(d)) => format!("{d}\n\n_Pending: an agent confirms and sharpens this during `kontext init` (task `purpose`)._"),
            _ => "_Pending: what this system does and for whom — written during `kontext init` (task `purpose`)._".to_string(),
        };
        Entry {
            id: "overview".into(),
            kind: "architecture".into(),
            title: format!("{} — architecture overview", app.project_name()),
            summary: inv.readme_summary.clone().or(inv.root_description.clone()).map(|s| util::truncate_chars(&s, 240)),
            tags: vec!["architecture".into()],
            body: format!("## Purpose\n\n{purpose}\n\n{}", facts_block(&facts)),
            rel_path: ov_rel.clone(),
            style: Style::Frontmatter,
            ..Default::default()
        }
    });
    if existing.is_some()
        && let Some(b) = replace_facts(&ov.body, &facts)
    {
        ov.body = b;
    }
    ov.set_extra("stack", FmValue::Str(stack_line(inv)));
    ov.set_extra("generated", FmValue::Str("kontext".into()));
    let text = ov.markdown();
    if std::fs::read_to_string(app.repo.abs(&ov_rel)).ok().as_deref() != Some(text.as_str()) {
        util::write_atomic(&app.repo.abs(&ov_rel), &text)?;
        rep.overview_written = true;
    }

    // modules
    for m in &mods {
        let rel = module_rel(&dir, m);
        let facts = module_facts(m, inv);
        let current = std::fs::read_to_string(app.repo.abs(&rel)).ok();
        let mut e = match &current {
            Some(t) => {
                let mut e = Entry::parse(&rel, t, "architecture");
                if let Some(b) = replace_facts(&e.body, &facts) {
                    e.body = b;
                }
                if e.get_extra("deepened").is_none() {
                    e.summary = m.description.clone().map(|d| util::truncate_chars(&util::one_line(&d), 200));
                }
                e
            }
            None => Entry {
                id: m.id.clone(),
                kind: "architecture".into(),
                title: m.path.clone(),
                summary: m.description.clone().map(|d| util::truncate_chars(&util::one_line(&d), 200)),
                body: format!(
                    "## Overview\n\n_Pending: an agent summarizes this module during `kontext init` (task `mod:{}`)._\n\n{}",
                    m.id.trim_start_matches("mod-"),
                    facts_block(&facts)
                ),
                rel_path: rel.clone(),
                style: Style::Frontmatter,
                ..Default::default()
            },
        };
        e.paths = vec![format!("{}/**", m.path)];
        let mut tags = vec!["module".to_string(), m.kind.clone()];
        let lang = m.language.to_lowercase();
        if !lang.is_empty() {
            tags.push(lang);
        }
        e.tags = tags;
        e.set_extra("rank", FmValue::Str(m.rank.to_string()));
        e.set_extra("fingerprint", FmValue::Str(m.fingerprint.clone()));
        e.set_extra("generated", FmValue::Str("kontext".into()));
        let text = e.markdown();
        if current.as_deref() != Some(text.as_str()) {
            util::write_atomic(&app.repo.abs(&rel), &text)?;
            if current.is_some() {
                rep.modules_updated += 1;
            } else {
                rep.modules_new += 1;
            }
        }
    }

    // index + merge strategy for it
    let (entries, _) = store.load_all();
    rep.index_changed = store.update_index_file(&entries)?;
    let ga = app.repo.abs(&format!("{dir}/.gitattributes"));
    if !ga.exists() {
        util::write_atomic(
            &ga,
            "# the generated index is re-rendered on every commit; union-merge keeps parallel branches conflict-free\nREADME.md merge=union\n",
        )?;
    }
    Ok(rep)
}

/// Replace the content under `## <heading>` (up to the next `## ` heading or the facts block).
pub fn replace_section(body: &str, heading: &str, content: &str) -> String {
    let marker = format!("## {heading}");
    let content = content.trim();
    let content = content.strip_prefix(&marker).map(str::trim).unwrap_or(content);
    match body.find(&marker) {
        Some(start) => {
            let after = start + marker.len();
            let rest = &body[after..];
            let end_rel = [rest.find("\n## "), rest.find(FACTS_START.split(" —").next().unwrap_or(FACTS_START))]
                .into_iter()
                .flatten()
                .min()
                .unwrap_or(rest.len());
            format!("{}{marker}\n\n{content}\n\n{}", &body[..start], rest[end_rel..].trim_start_matches('\n'))
        }
        None => format!("{marker}\n\n{content}\n\n{}", body.trim_start()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sections() {
        let body = format!("## Overview\n\n_Pending_\n\n{}", facts_block("## Facts\n- a"));
        let b = replace_section(&body, "Overview", "It crawls.\n\nMore.");
        assert!(b.starts_with("## Overview\n\nIt crawls.\n\nMore.\n\n<!-- kontext:facts:start"));
        let b2 = replace_facts(&b, "## Facts\n- b").unwrap();
        assert!(b2.contains("- b") && !b2.contains("- a") && b2.contains("It crawls."));
        let c = replace_section("## Purpose\n\nold\n\n## Stack\nx\n", "Purpose", "## Purpose\nnew");
        assert_eq!(c, "## Purpose\n\nnew\n\n## Stack\nx\n");
    }
}
