//! The team store: short Markdown entries (decisions, conventions, learnings, incidents, architecture)
//! living in the repository, reviewed like code.
//!
//! Two on-disk styles are understood:
//! * `frontmatter` — YAML-ish front matter (flat keys, inline or dashed lists) + Markdown body;
//! * `fields` — classic ADR files: `# 0002 — Title` followed by `**Status:** accepted` style lines.
use crate::config::{Config, Numbering, Style};
use crate::repo::Repo;
use crate::util;
use anyhow::{Result, bail};
use regex::Regex;
use std::collections::{BTreeMap, HashSet};
use std::path::Path;
use std::sync::LazyLock;

pub const DECISION_STATUSES: &[&str] = &["proposed", "accepted", "superseded", "deprecated", "rejected"];
pub const INDEX_START: &str = "<!-- kontext:index:start — generated by kontext; edits between these markers are overwritten -->";
pub const INDEX_END: &str = "<!-- kontext:index:end -->";

#[derive(Debug, Clone, PartialEq)]
pub enum FmValue {
    Str(String),
    List(Vec<String>),
}

impl FmValue {
    pub fn as_str(&self) -> String {
        match self {
            FmValue::Str(s) => s.clone(),
            FmValue::List(l) => l.join(", "),
        }
    }
    pub fn as_list(&self) -> Vec<String> {
        match self {
            FmValue::Str(s) => split_inline_list(s),
            FmValue::List(l) => l.clone(),
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct Entry {
    pub id: String,
    pub kind: String,
    pub title: String,
    pub status: Option<String>,
    pub date: Option<String>,
    pub summary: Option<String>,
    pub tags: Vec<String>,
    pub paths: Vec<String>,
    pub supersedes: Vec<String>,
    pub superseded_by: Vec<String>,
    pub commits: Vec<String>,
    pub author: Option<String>,
    pub visibility: Option<String>,
    pub origin: Option<String>,
    pub extra: Vec<(String, FmValue)>,
    pub body: String,
    pub rel_path: String,
    pub style: Style,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Level {
    Warn,
    Error,
}

#[derive(Debug, Clone)]
pub struct Issue {
    pub level: Level,
    pub path: String,
    pub msg: String,
}

impl std::fmt::Display for Issue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let lvl = match self.level {
            Level::Error => "error",
            Level::Warn => "warn",
        };
        write!(f, "{lvl}: {}: {}", self.path, self.msg)
    }
}

impl Entry {
    pub fn get_extra(&self, key: &str) -> Option<String> {
        self.extra.iter().find(|(k, _)| k == key).map(|(_, v)| v.as_str())
    }

    pub fn set_extra(&mut self, key: &str, value: FmValue) {
        if let Some(slot) = self.extra.iter_mut().find(|(k, _)| k == key) {
            slot.1 = value;
        } else {
            self.extra.push((key.to_string(), value));
        }
    }

    pub fn is_active(&self) -> bool {
        !matches!(self.status.as_deref(), Some("superseded" | "deprecated" | "rejected"))
    }

    /// `0002` for sequentially numbered ADRs, otherwise the full id.
    pub fn short_id(&self) -> String {
        let digits: String = self.id.chars().take_while(|c| c.is_ascii_digit()).collect();
        let dated = self.id.get(..10).is_some_and(|d| chrono::NaiveDate::parse_from_str(d, "%Y-%m-%d").is_ok());
        if !dated && (3..=5).contains(&digits.len()) && self.id[digits.len()..].starts_with('-') {
            return digits;
        }
        self.id.clone()
    }

    /// One-line summary: explicit `summary`, else the first paragraph of `## Decision`, else of the body.
    pub fn summary_text(&self, max: usize) -> String {
        if let Some(s) = self.summary.as_ref().filter(|s| !s.trim().is_empty()) {
            return util::truncate_chars(&util::one_line(s), max);
        }
        for heading in ["## Decision", "## Summary", "## Overview", "## Purpose"] {
            if let Some(pos) = self.body.find(heading) {
                let after = &self.body[pos + heading.len()..];
                let after = after.split_once('\n').map(|(_, r)| r).unwrap_or("");
                let p = util::first_paragraph(after, max);
                if !p.is_empty() && !p.starts_with("_Pending") {
                    return p;
                }
            }
        }
        let p = util::first_paragraph(&self.body, max);
        if p.starts_with("_Pending") || p.starts_with("Pending:") { String::new() } else { p }
    }

    /// What the entry says to do: the first paragraph of `## Decision` when there is one, else the
    /// summary. A summary often states the goal and leaves the rule itself out ("error pages are no
    /// content" versus "reject them and try the next engine"), and the rule is what a change is checked against.
    pub fn rule_text(&self, max: usize) -> String {
        if let Some(pos) = self.body.find("## Decision") {
            let after = &self.body[pos + "## Decision".len()..];
            let after = after.split_once('\n').map(|(_, r)| r).unwrap_or("");
            let p = util::first_paragraph(after, max);
            if !p.is_empty() && !p.starts_with("_Pending") {
                return p;
            }
        }
        self.summary_text(max)
    }

    pub fn l0(&self, max: usize) -> String {
        let s = self.summary_text(max);
        if s.is_empty() { self.title.clone() } else { format!("{} — {}", self.title, s) }
    }

    pub fn markdown(&self) -> String {
        match self.style {
            Style::Frontmatter => self.to_frontmatter_md(),
            Style::Fields => self.to_fields_md(),
        }
    }

    fn fm_pairs(&self) -> Vec<(String, FmValue)> {
        let mut v: Vec<(String, FmValue)> = Vec::new();
        let mut s = |k: &str, val: &Option<String>| {
            if let Some(x) = val.as_ref().filter(|x| !x.is_empty()) {
                v.push((k.into(), FmValue::Str(x.clone())));
            }
        };
        s("id", &Some(self.id.clone()));
        s("kind", &Some(self.kind.clone()));
        s("title", &Some(self.title.clone()));
        s("status", &self.status);
        s("date", &self.date);
        s("summary", &self.summary);
        let mut l = |k: &str, val: &Vec<String>| {
            if !val.is_empty() {
                v.push((k.into(), FmValue::List(val.clone())));
            }
        };
        l("tags", &self.tags);
        l("paths", &self.paths);
        l("supersedes", &self.supersedes);
        l("superseded_by", &self.superseded_by);
        l("commits", &self.commits);
        let mut s2 = |k: &str, val: &Option<String>| {
            if let Some(x) = val.as_ref().filter(|x| !x.is_empty()) {
                v.push((k.into(), FmValue::Str(x.clone())));
            }
        };
        s2("author", &self.author);
        s2("visibility", &self.visibility);
        s2("origin", &self.origin);
        v.extend(self.extra.iter().cloned());
        v
    }

    fn to_frontmatter_md(&self) -> String {
        let mut out = String::from("---\n");
        for (k, v) in self.fm_pairs() {
            match v {
                FmValue::Str(s) => out.push_str(&format!("{k}: {}\n", fm_scalar(&s))),
                FmValue::List(l) => out.push_str(&format!("{k}: [{}]\n", l.iter().map(|x| fm_list_item(x)).collect::<Vec<_>>().join(", "))),
            }
        }
        out.push_str("---\n\n");
        out.push_str(self.body.trim_start_matches('\n'));
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out
    }

    fn to_fields_md(&self) -> String {
        let short = self.short_id();
        let heading = if short != self.id { format!("# {short} — {}", self.title) } else { format!("# {}", self.title) };
        let mut out = format!("{heading}\n\n");
        let mut field = |k: &str, v: String| {
            if !v.is_empty() {
                out.push_str(&format!("**{k}:** {v}\n"));
            }
        };
        field("Status", self.status.clone().unwrap_or_default());
        field("Date", self.date.clone().unwrap_or_default());
        field("Summary", self.summary.clone().unwrap_or_default());
        field("Tags", self.tags.join(", "));
        field("Paths", self.paths.join(", "));
        field("Supersedes", self.supersedes.join(", "));
        field("Superseded by", self.superseded_by.join(", "));
        field("Commits", self.commits.join(", "));
        field("Author", self.author.clone().unwrap_or_default());
        out.push('\n');
        out.push_str(self.body.trim_start_matches('\n'));
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out
    }
}

// ---------------------------------------------------------------------------------------------
// Front matter (a deliberately small YAML subset: flat keys, scalars, inline or dashed lists)

pub fn split_frontmatter(text: &str) -> Option<(&str, &str)> {
    let t = text.strip_prefix('\u{feff}').unwrap_or(text);
    let rest = t.strip_prefix("---\n").or_else(|| t.strip_prefix("---\r\n"))?;
    let mut idx = 0;
    for line in rest.split_inclusive('\n') {
        let trimmed = line.trim_end();
        if trimmed == "---" || trimmed == "..." {
            return Some((&rest[..idx], &rest[idx + line.len()..]));
        }
        idx += line.len();
    }
    None
}

pub fn parse_fm(fm: &str) -> Vec<(String, FmValue)> {
    let mut out: Vec<(String, FmValue)> = Vec::new();
    let mut open: Option<usize> = None; // last key with an empty inline value (list or block scalar)
    let mut block = false;
    for raw in fm.lines() {
        let t = raw.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        let indented = raw.starts_with(' ') || raw.starts_with('\t');
        if let Some(i) = open {
            if t.starts_with("- ") || t == "-" {
                let item = unquote(t.trim_start_matches('-').trim());
                if let FmValue::List(l) = &mut out[i].1 {
                    l.push(item);
                    continue;
                }
            }
            if indented {
                match &mut out[i].1 {
                    FmValue::Str(s) => {
                        if !s.is_empty() {
                            s.push(if block { '\n' } else { ' ' });
                        }
                        s.push_str(t);
                    }
                    FmValue::List(l) if l.is_empty() => out[i].1 = FmValue::Str(t.to_string()),
                    FmValue::List(_) => {}
                }
                continue;
            }
        }
        let Some((k, v)) = t.split_once(':') else { continue };
        let key = k.trim().to_string();
        let v = v.trim();
        open = None;
        block = false;
        if v.is_empty() {
            out.push((key, FmValue::List(Vec::new())));
            open = Some(out.len() - 1);
        } else if v.starts_with('[') && v.ends_with(']') {
            out.push((key, FmValue::List(split_inline_list(&v[1..v.len() - 1]))));
        } else if matches!(v, "|" | "|-" | ">" | ">-") {
            out.push((key, FmValue::Str(String::new())));
            open = Some(out.len() - 1);
            block = v.starts_with('|');
        } else {
            out.push((key, FmValue::Str(unquote(v))));
        }
    }
    out
}

pub fn split_inline_list(s: &str) -> Vec<String> {
    let mut items = Vec::new();
    let mut cur = String::new();
    let mut quote: Option<char> = None;
    for c in s.chars() {
        match (quote, c) {
            (None, '"' | '\'') => {
                quote = Some(c);
                cur.push(c);
            }
            (Some(q), c) if c == q => {
                quote = None;
                cur.push(c);
            }
            (None, ',') => {
                items.push(std::mem::take(&mut cur));
            }
            _ => cur.push(c),
        }
    }
    items.push(cur);
    items.into_iter().map(|x| unquote(x.trim())).filter(|x| !x.is_empty()).collect()
}

fn unquote(s: &str) -> String {
    let s = s.trim();
    if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        return s[1..s.len() - 1].replace("\\\"", "\"").replace("\\\\", "\\");
    }
    if s.len() >= 2 && s.starts_with('\'') && s.ends_with('\'') {
        return s[1..s.len() - 1].replace("''", "'");
    }
    // strip trailing comments (" # ...") on plain scalars
    match s.find(" #") {
        Some(i) => s[..i].trim_end().to_string(),
        None => s.to_string(),
    }
}

fn needs_quotes(s: &str) -> bool {
    s.is_empty()
        || s != s.trim()
        || s.contains(": ")
        || s.contains(" #")
        || s.ends_with(':')
        || s.starts_with(['-', '?', ':', ',', '[', ']', '{', '}', '#', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`'])
        || matches!(s.to_lowercase().as_str(), "true" | "false" | "null" | "yes" | "no" | "~" | "on" | "off")
}

fn fm_scalar(s: &str) -> String {
    let s = s.replace('\n', " ");
    if needs_quotes(&s) { format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")) } else { s }
}

fn fm_list_item(s: &str) -> String {
    if needs_quotes(s) || s.contains([',', '[', ']']) {
        format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        s.to_string()
    }
}

// ---------------------------------------------------------------------------------------------
// Parsing entries

static TITLE_NUM: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"^(?:ADR[-\s]?)?(\d{1,5})\s*[—–:.\-]+\s*(.+)$").unwrap());
static FIELD: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"^\s*(?:[-*+]\s+)?(?:\*\*|__)?([A-Za-z][A-Za-z _-]{0,30}?)(?:\*\*|__)?\s*:\s*(?:\*\*|__)?\s*(.+?)\s*$").unwrap()
});

const FIELD_KEYS: &[&str] = &[
    "status",
    "date",
    "tags",
    "paths",
    "supersedes",
    "superseded by",
    "superseded-by",
    "summary",
    "commits",
    "author",
    "authors",
    "deciders",
    "owner",
    "scope",
    "kind",
    "id",
];

pub fn normalize_status(raw: &str) -> String {
    let word: String = raw
        .trim()
        .trim_start_matches(['*', '_', '`'])
        .chars()
        .take_while(|c| c.is_alphabetic() || *c == '-')
        .collect::<String>()
        .to_lowercase();
    match word.as_str() {
        "approved" | "done" | "adopted" | "active" | "implemented" => "accepted".into(),
        "draft" | "proposal" | "open" | "pending" => "proposed".into(),
        "replaced" | "obsolete" => "superseded".into(),
        "declined" | "abandoned" => "rejected".into(),
        _ => word,
    }
}

fn humanize(stem: &str) -> String {
    let s = stem.trim_start_matches(|c: char| c.is_ascii_digit() || c == '-');
    let s = if s.is_empty() { stem } else { s };
    let mut t = s.replace(['-', '_'], " ");
    if let Some(first) = t.get(0..1) {
        t = first.to_uppercase() + &t[1..];
    }
    t
}

fn first_h1(body: &str) -> Option<(usize, String)> {
    let mut in_code = false;
    let mut off = 0;
    for line in body.split_inclusive('\n') {
        let t = line.trim();
        if t.starts_with("```") {
            in_code = !in_code;
        }
        if !in_code && t.starts_with("# ") {
            return Some((off, t[2..].trim().to_string()));
        }
        off += line.len();
    }
    None
}

impl Entry {
    pub fn parse(rel_path: &str, text: &str, default_kind: &str) -> Entry {
        let stem = Path::new(rel_path).file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
        let mut e = Entry { rel_path: rel_path.to_string(), kind: default_kind.to_string(), ..Default::default() };
        if let Some((fm, body)) = split_frontmatter(text) {
            e.style = Style::Frontmatter;
            e.body = body.trim_start_matches(['\n', '\r']).to_string();
            for (k, v) in parse_fm(fm) {
                e.apply_field(&k.to_lowercase(), v);
            }
        } else {
            e.style = Style::Fields;
            e.parse_fields(text);
        }
        if e.id.is_empty() {
            e.id = stem.clone();
        }
        if e.title.is_empty() {
            e.title = first_h1(&e.body).map(|(_, t)| t).unwrap_or_else(|| humanize(&stem));
        }
        if let Some(s) = &e.status {
            e.status = Some(normalize_status(s));
        }
        e
    }

    fn apply_field(&mut self, key: &str, v: FmValue) {
        match key {
            "id" => self.id = v.as_str(),
            "kind" | "type" => self.kind = v.as_str().to_lowercase(),
            "title" => self.title = v.as_str(),
            "status" => {
                let raw = v.as_str();
                let lower = raw.to_lowercase();
                if let Some(rest) = lower.strip_prefix("superseded by") {
                    let ids = split_inline_list(rest.trim_start_matches([':', ' ']));
                    self.superseded_by.extend(ids);
                }
                self.status = Some(raw);
            }
            "date" | "decided" | "created" => {
                if self.date.is_none() {
                    self.date = Some(v.as_str())
                }
            }
            "summary" | "description" => self.summary = Some(v.as_str()),
            "tags" => self.tags = v.as_list(),
            "paths" | "scope" if matches!(v, FmValue::List(_)) || key == "paths" => self.paths = v.as_list(),
            "supersedes" => self.supersedes = v.as_list(),
            "superseded_by" | "superseded by" | "superseded-by" => self.superseded_by = v.as_list(),
            "commits" => self.commits = v.as_list(),
            "author" | "authors" | "deciders" | "owner" => {
                if self.author.is_none() {
                    self.author = Some(v.as_str())
                }
            }
            "visibility" => self.visibility = Some(v.as_str()),
            "origin" => self.origin = Some(v.as_str()),
            _ => self.extra.push((key.to_string(), v)),
        }
    }

    fn parse_fields(&mut self, text: &str) {
        let (h1_off, raw_title) = match first_h1(text) {
            Some(x) => x,
            None => {
                self.body = text.to_string();
                return;
            }
        };
        if let Some(c) = TITLE_NUM.captures(&raw_title) {
            self.title = c[2].trim().to_string();
        } else {
            self.title = raw_title.clone();
        }
        let after_title = &text[h1_off..];
        let after_title = after_title.split_once('\n').map(|(_, r)| r).unwrap_or("");
        let mut consumed = 0;
        let mut saw_field = false;
        for line in after_title.split_inclusive('\n') {
            let t = line.trim();
            if t.starts_with("## ") || t.starts_with("# ") {
                break;
            }
            if t.is_empty() {
                consumed += line.len();
                continue;
            }
            match FIELD.captures(t) {
                Some(c) if FIELD_KEYS.contains(&c[1].trim().to_lowercase().as_str()) => {
                    let key = c[1].trim().to_lowercase();
                    let val = c[2].trim().trim_end_matches("**").trim().to_string();
                    let v = if matches!(key.as_str(), "tags" | "paths" | "supersedes" | "superseded by" | "superseded-by" | "commits") {
                        FmValue::List(split_inline_list(&val.replace('`', "")))
                    } else {
                        FmValue::Str(val)
                    };
                    self.apply_field(&key, v);
                    saw_field = true;
                    consumed += line.len();
                }
                _ => break,
            }
        }
        let preamble = &text[..h1_off];
        let rest = &after_title[consumed..];
        self.body = if saw_field || preamble.trim().is_empty() { rest.trim_start_matches('\n').to_string() } else { text.to_string() };
    }
}

// ---------------------------------------------------------------------------------------------
// Store

pub struct Store<'a> {
    pub repo: &'a Repo,
    pub cfg: &'a Config,
}

impl<'a> Store<'a> {
    pub fn new(repo: &'a Repo, cfg: &'a Config) -> Store<'a> {
        Store { repo, cfg }
    }

    pub fn dir(&self) -> String {
        self.cfg.store.dir.trim_end_matches('/').to_string()
    }

    pub fn index_path(&self) -> String {
        format!("{}/README.md", self.dir())
    }

    fn kind_paths(&self) -> Vec<(String, String)> {
        let mut v: Vec<(String, String)> = self.cfg.kind_names().into_iter().map(|k| (self.cfg.kind_path(&k), k)).collect();
        v.sort_by_key(|x| std::cmp::Reverse(x.0.len()));
        v
    }

    pub fn kind_for_path(&self, rel: &str) -> Option<String> {
        self.kind_paths().into_iter().find(|(p, _)| rel.starts_with(&format!("{p}/"))).map(|(_, k)| k)
    }

    pub fn is_entry_path(&self, rel: &str) -> bool {
        if !rel.ends_with(".md") {
            return false;
        }
        let name = rel.rsplit('/').next().unwrap_or(rel);
        if is_non_entry_name(name) {
            return false;
        }
        self.kind_for_path(rel).is_some()
    }

    /// Any path kontext manages (entries, index, shared config).
    pub fn is_store_path(&self, rel: &str) -> bool {
        self.is_entry_path(rel) || rel == self.index_path() || rel.starts_with(&format!("{}/", self.dir()))
    }

    pub fn load_all(&self) -> (Vec<Entry>, Vec<String>) {
        let mut entries = Vec::new();
        let mut errors = Vec::new();
        let mut seen = HashSet::new();
        for (path, kind) in self.kind_paths() {
            let abs = self.repo.abs(&path);
            let mut files = Vec::new();
            collect_md(&abs, &mut files);
            files.sort();
            for f in files {
                let Some(rel) = self.repo.rel(&f) else { continue };
                if !seen.insert(rel.clone()) || !self.is_entry_path(&rel) {
                    continue;
                }
                match std::fs::read_to_string(&f) {
                    Ok(text) => {
                        let e = Entry::parse(&rel, &text, &kind);
                        entries.push(e);
                    }
                    Err(err) => errors.push(format!("{rel}: {err}")),
                }
            }
        }
        (entries, errors)
    }

    pub fn find<'e>(entries: &'e [Entry], key: &str) -> Option<&'e Entry> {
        let key = key.trim().trim_start_matches("kx:");
        entries
            .iter()
            .find(|e| e.id == key)
            .or_else(|| entries.iter().find(|e| e.short_id() == key))
            .or_else(|| entries.iter().find(|e| e.rel_path == key))
            .or_else(|| {
                let m: Vec<_> = entries.iter().filter(|e| e.id.starts_with(key)).collect();
                if m.len() == 1 { Some(m[0]) } else { None }
            })
    }

    /// Choose an id and file path for a new entry of `kind`.
    pub fn allocate(&self, kind: &str, title: &str, date: &str) -> (String, String) {
        let dir = self.cfg.kind_path(kind);
        let slug = {
            let s = util::slugify(title, 60);
            if s.is_empty() { "entry".to_string() } else { s }
        };
        let base = match self.cfg.kind_numbering(kind) {
            Numbering::Sequential => {
                let (next, width) = self.next_number(&dir);
                format!("{:0width$}-{slug}", next, width = width)
            }
            Numbering::Date => format!("{date}-{slug}"),
            Numbering::None => slug,
        };
        let mut id = base.clone();
        let mut n = 2;
        while self.repo.abs(&format!("{dir}/{id}.md")).exists() {
            id = format!("{base}-{n}");
            n += 1;
        }
        (id.clone(), format!("{dir}/{id}.md"))
    }

    fn next_number(&self, dir: &str) -> (usize, usize) {
        let mut max = 0usize;
        let mut width = 4usize;
        if let Ok(rd) = std::fs::read_dir(self.repo.abs(dir)) {
            for e in rd.flatten() {
                let name = e.file_name().to_string_lossy().to_string();
                let digits: String = name.chars().take_while(|c| c.is_ascii_digit()).collect();
                if digits.len() >= 3 && name[digits.len()..].starts_with('-') {
                    width = digits.len();
                    max = max.max(digits.parse().unwrap_or(0));
                }
            }
        }
        (max + 1, width)
    }

    /// Write a new entry into the working tree (not staged). Fills id, path and style when missing.
    pub fn write_new(&self, e: &mut Entry) -> Result<String> {
        if !self.cfg.store.kinds.contains_key(&e.kind) {
            bail!("unknown kind '{}' (known: {})", e.kind, self.cfg.kind_names().join(", "));
        }
        let date = e.date.clone().unwrap_or_else(util::today);
        let (id, rel) = self.allocate(&e.kind, &e.title, &date);
        e.id = id;
        e.rel_path = rel.clone();
        e.style = self.cfg.kind_style(&e.kind);
        if e.date.is_none() {
            e.date = Some(date);
        }
        util::write_atomic(&self.repo.abs(&rel), &e.markdown())?;
        Ok(rel)
    }

    /// Mark `old` as superseded by `new_id`, editing the file in place.
    pub fn mark_superseded(&self, old: &Entry, new_id: &str) -> Result<()> {
        let abs = self.repo.abs(&old.rel_path);
        let text = std::fs::read_to_string(&abs)?;
        let updated = match old.style {
            Style::Frontmatter => {
                let mut e = old.clone();
                e.status = Some("superseded".into());
                if !e.superseded_by.iter().any(|x| x == new_id) {
                    e.superseded_by.push(new_id.to_string());
                }
                e.markdown()
            }
            Style::Fields => {
                static STATUS_LINE: LazyLock<Regex> = LazyLock::new(|| {
                    Regex::new(r"(?mi)^(\s*(?:[-*+]\s+)?(?:\*\*|__)?status(?:\*\*|__)?\s*:\s*(?:\*\*|__)?\s*).*$").unwrap()
                });
                if STATUS_LINE.is_match(&text) {
                    STATUS_LINE.replace(&text, format!("${{1}}superseded by {new_id}")).into_owned()
                } else {
                    text.clone()
                }
            }
        };
        if updated != text {
            util::write_atomic(&abs, &updated)?;
        }
        Ok(())
    }

    pub fn validate(&self, e: &Entry, known_ids: &HashSet<String>, tracked: Option<&[String]>) -> Vec<Issue> {
        let mut issues = Vec::new();
        let mut push = |level, msg: String| issues.push(Issue { level, path: e.rel_path.clone(), msg });
        if e.title.trim().is_empty() {
            push(Level::Error, "missing title".into());
        }
        if !self.cfg.store.kinds.contains_key(&e.kind) {
            push(Level::Error, format!("unknown kind '{}'", e.kind));
        }
        if e.kind == "decision" {
            match e.status.as_deref() {
                None => push(Level::Warn, "decision has no status (proposed|accepted|superseded|deprecated|rejected)".into()),
                Some(s) if !DECISION_STATUSES.contains(&s) => push(Level::Warn, format!("unusual decision status '{s}'")),
                _ => {}
            }
            if e.date.is_none() {
                push(Level::Warn, "decision has no date".into());
            }
        }
        if let Some(d) = &e.date {
            let ok = d.get(..10).is_some_and(|x| chrono::NaiveDate::parse_from_str(x, "%Y-%m-%d").is_ok());
            if !ok {
                push(Level::Warn, format!("date '{d}' is not YYYY-MM-DD"));
            }
        }
        let lines = e.body.lines().filter(|l| !l.trim().is_empty()).count();
        let max = self.cfg.store.max_body_lines;
        if max > 0 && lines > max && e.get_extra("generated").is_none() {
            push(Level::Warn, format!("long entry ({lines} lines > {max}) — keep entries brief and link to docs for detail"));
        }
        for s in &e.supersedes {
            if !known_ids.contains(s) && !known_ids.iter().any(|k| k.starts_with(&format!("{s}-"))) {
                push(Level::Warn, format!("supersedes unknown entry '{s}'"));
            }
        }
        if let Some(files) = tracked {
            for p in &e.paths {
                if !files.iter().any(|f| crate::glob::path_matches(p, f)) {
                    push(Level::Warn, format!("path pattern '{p}' matches no tracked file"));
                }
            }
        }
        issues
    }

    // -------------------------------------------------------------------------------- index file

    pub fn render_index(&self, entries: &[Entry]) -> String {
        let store_dir = self.dir();
        let depth = store_dir.split('/').filter(|s| !s.is_empty()).count();
        let link = |rel: &str| -> String {
            match rel.strip_prefix(&format!("{store_dir}/")) {
                Some(inside) => inside.to_string(),
                None => format!("{}{}", "../".repeat(depth), rel),
            }
        };
        let mut by_kind: BTreeMap<&str, Vec<&Entry>> = BTreeMap::new();
        for e in entries {
            by_kind.entry(e.kind.as_str()).or_default().push(e);
        }
        let order = ["decision", "convention", "learning", "incident", "architecture"];
        let mut kinds: Vec<&str> = by_kind.keys().copied().collect();
        kinds.sort_by_key(|k| order.iter().position(|o| o == k).unwrap_or(order.len()));
        let mut out = String::new();
        for k in kinds {
            let mut list = by_kind[k].clone();
            if k == "decision" || k == "incident" || k == "learning" {
                list.sort_by(|a, b| b.date.cmp(&a.date).then(a.id.cmp(&b.id)));
            } else {
                list.sort_by(|a, b| {
                    let rank = |e: &Entry| if e.id == "overview" { 0 } else { 1 };
                    rank(a).cmp(&rank(b)).then(a.rel_path.cmp(&b.rel_path))
                });
            }
            out.push_str(&format!("\n## {}\n\n", kind_heading(k)));
            for e in list {
                let date = e.date.as_deref().map(|d| format!("{} · ", d.chars().take(10).collect::<String>())).unwrap_or_default();
                let status = e.status.as_deref().filter(|_| k == "decision").map(|s| format!(" · {s}")).unwrap_or_default();
                let summary = e.summary_text(110);
                let summary = if summary.is_empty() { String::new() } else { format!(" — {summary}") };
                out.push_str(&format!("- {date}[{}]({}){status}{summary}\n", e.title.replace(['[', ']'], ""), link(&e.rel_path)));
            }
        }
        out
    }

    /// Rewrite the generated part of `<store>/README.md`. Returns true when the file changed.
    pub fn update_index_file(&self, entries: &[Entry]) -> Result<bool> {
        let rel = self.index_path();
        let abs = self.repo.abs(&rel);
        let generated = format!("{INDEX_START}\n{}\n{INDEX_END}\n", self.render_index(entries).trim_end());
        let current = std::fs::read_to_string(&abs).ok();
        let next = match &current {
            Some(text) => match (text.find(INDEX_START), text.find(INDEX_END)) {
                (Some(s), Some(e)) if e > s => {
                    format!("{}{}{}", &text[..s], generated, text[e + INDEX_END.len()..].trim_start_matches('\n'))
                }
                _ => format!("{}\n\n{}", text.trim_end(), generated),
            },
            None => format!("{}\n{}", INDEX_PREAMBLE.trim_start(), generated),
        };
        if current.as_deref() == Some(next.as_str()) {
            return Ok(false);
        }
        util::write_atomic(&abs, &next)?;
        Ok(true)
    }
}

const INDEX_PREAMBLE: &str = r#"
# Team context

Shared, reviewed knowledge for people and coding agents: decisions, conventions, learnings,
incidents and the architecture map. Entries are short Markdown files and change through normal
code review, like the code they describe.

- Agents with the `kontext` MCP server: call `ctx_brief` first, `ctx_capture` when something
  durable is decided, and `ctx_prepare_commit` before committing.
- People: `kontext log` (decision timeline), `kontext why <path>`, `kontext capture`.
"#;

fn kind_heading(k: &str) -> String {
    match k {
        "decision" => "Decisions".into(),
        "convention" => "Conventions".into(),
        "learning" => "Learnings".into(),
        "incident" => "Incidents".into(),
        "architecture" => "Architecture".into(),
        other => {
            let mut s = other.to_string();
            if let Some(f) = s.get(0..1) {
                s = f.to_uppercase() + &s[1..];
            }
            s
        }
    }
}

pub fn is_non_entry_name(name: &str) -> bool {
    let l = name.to_lowercase();
    l == "readme.md" || l == "index.md" || l.starts_with("template") || l.starts_with("0000-") || l.starts_with('_') || l.starts_with('.')
}

fn collect_md(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        let name = e.file_name().to_string_lossy().to_string();
        if name.starts_with('.') || name == "node_modules" {
            continue;
        }
        match e.file_type() {
            Ok(t) if t.is_dir() => collect_md(&p, out),
            Ok(t) if t.is_file() && name.ends_with(".md") => out.push(p),
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frontmatter_roundtrip() {
        let text = "---\nid: 2026-09-28-use-tantivy\nkind: decision\ntitle: \"Use Tantivy: fast BM25\"\nstatus: Accepted\ndate: 2026-09-28\ntags: [search, rust]\npaths:\n  - src/index.rs\n  - \"src/a, b.rs\"\nreviewers: [x]\n---\n\n## Context\nWe need search.\n\n## Decision\nUse Tantivy for local recall.\n";
        let e = Entry::parse(".ai/decisions/2026-09-28-use-tantivy.md", text, "decision");
        assert_eq!(e.title, "Use Tantivy: fast BM25");
        assert_eq!(e.status.as_deref(), Some("accepted"));
        assert_eq!(e.paths, vec!["src/index.rs", "src/a, b.rs"]);
        assert_eq!(e.tags, vec!["search", "rust"]);
        assert_eq!(e.summary_text(100), "Use Tantivy for local recall.");
        assert_eq!(e.extra[0].0, "reviewers");
        let again = Entry::parse(&e.rel_path, &e.markdown(), "decision");
        assert_eq!(again.title, e.title);
        assert_eq!(again.paths, e.paths);
        assert_eq!(again.extra, e.extra);
        assert_eq!(again.body.trim(), e.body.trim());
    }

    #[test]
    fn fields_style_adr() {
        let text = "# 0002 — Orders live in PostgreSQL\n\n**Status:** accepted\n**Date:** 2026-08-04\n\n## Context\n\nOrders need transactions across items and payments.\n\n## Decision\n\nOne PostgreSQL database. Reporting reads a replica.\n";
        let e = Entry::parse("docs/adr/0002-orders-in-postgresql.md", text, "decision");
        assert_eq!(e.id, "0002-orders-in-postgresql");
        assert_eq!(e.short_id(), "0002");
        assert_eq!(e.title, "Orders live in PostgreSQL");
        assert_eq!(e.status.as_deref(), Some("accepted"));
        assert_eq!(e.date.as_deref(), Some("2026-08-04"));
        assert!(e.body.starts_with("## Context"));
        assert_eq!(e.summary_text(200), "One PostgreSQL database. Reporting reads a replica.");
        let md = e.markdown();
        assert!(md.starts_with("# 0002 — Orders live in PostgreSQL\n\n**Status:** accepted\n"));
    }

    #[test]
    fn status_variants() {
        assert_eq!(normalize_status("Accepted (2026-08-04)"), "accepted");
        assert_eq!(normalize_status("**Draft**"), "proposed");
        let e = Entry::parse("docs/adr/0003-x.md", "# ADR-3: X\n\n* Status: Superseded by 0007\n\nBody.\n", "decision");
        assert_eq!(e.status.as_deref(), Some("superseded"));
        assert_eq!(e.superseded_by, vec!["0007"]);
        assert_eq!(e.title, "X");
    }
}
